### ISSUE TITLE
Nov 24

### ISSUE THREAD

**Issue by tshemsedinov** [kse-ua/introduction-to-it#12]

**Comment by kpetrynka** [comment]
https://github.com/kpetrynka/github.git

**Comment by mlastovski** [comment]
https://github.com/shulevskyi/kse-hw @mlastovski @shulevskyi

**Comment by Isaevnikita** [comment]
https://github.com/Isaevnikita/hometask.git

**Comment by LieTieOsu** [comment]
https://github.com/LieTieOsu/social-credit-system

**Comment by bugarenko** [comment]
https://github.com/bugarenko/Bugarenko

**Comment by Zakhar-Khmurych** [comment]
https://github.com/Zakhar-Khmurych/Code-fixes/issues

**Comment by tonyblackbird** [comment]
https://github.com/tonyblackbird/introduction-to-it

**Comment by YaroslavKSE** [comment]
https://github.com/YaroslavKSE/Homework

**Comment by amyslytska** [comment]
https://github.com/amyslytska/Task-1

**Comment by Selbonyka** [comment]
https://github.com/Selbonyka/LessonRepo

**Comment by mlastovski** [comment]
https://github.com/mlastovski/kse-sum

**Comment by Egor01b** [comment]
https://github.com/Egor01b/Egor01b

**Comment by okorshunovs** [comment]
https://github.com/okorshunovs/test2

**Comment by kmirik999** [comment]
https://github.com/kmirik999/Kryvoruchko-Myroslav

**Comment by complectzero** [comment]
https://github.com/complectzero/zeropractic

**Comment by nastia4464** [comment]
https://github.com/nastia4464/Ansstasia-Poimanova.git

**Comment by istepmother** [comment]
https://github.com/istepmother/propername

**Comment by UlianaMakhno** [comment]
https://github.com/UlianaMakhno/code-errors.git

**Comment by ISukhoiarska** [comment]
https://github.com/ISukhoiarska/Fixing.git

**Comment by msherinn** [comment]
https://github.com/msherinn/term2.git

**Comment by Arsenii1** [comment]
https://github.com/Arsenii1/newrepo

**Comment by DenisMilkevich** [comment]
https://github.com/DenisMilkevich/ABOBA/tree/main

**Comment by shulevskyi** [comment]
https://github.com/shulevskyi/kse-hw

**Comment by ykhadnevich** [comment]
https://github.com/ykhadnevich/Special_for_you

**Comment by Kate732** [comment]
https://github.com/Kate732/JavaScript

**Comment by Ann-the-programmer** [comment]
https://github.com/Ann-the-programmer/Fixing_codes.git

**Comment by qualia4** [comment]
https://github.com/qualia4/lecture2-task

**Comment by omostovyijr** [comment]
https://github.com/omostovyijr/TasksForLecture8

**Comment by roflmyrlok** [comment]
https://github.com/roflmyrlok/brandone_6.git

**Comment by tshemsedinov** [comment]
--- Break ---

**Comment by AvangardAA** [comment]
https://github.com/AvangardAA/kse-sum

**Comment by marchellodev** [comment]
https://github.com/torvalds/linux/

**Comment by anastassiafugier** [comment]
https://github.com/anastassiafugier/1st-repository.git
