### ISSUE TITLE
Nov 26

### ISSUE THREAD

**Issue by tshemsedinov** [kse-ua/introduction-to-it#17]
14

**Comment by amyslytska** [comment]
https://github.com/amyslytska

**Comment by LieTieOsu** [comment]
https://github.com/LieTieOsu

**Comment by Ann-the-programmer** [comment]
https://github.com/Ann-the-programmer

**Comment by kpetrynka** [comment]
https://github.com/kpetrynka

**Comment by UlianaMakhno** [comment]
https://github.com/UlianaMakhno

**Comment by tonyblackbird** [comment]
https://github.com/tonyblackbird

**Comment by tonyblackbird** [comment]
https://github.com/kse-ua/introduction-to-it/pull/16

**Comment by Zakhar-Khmurych** [comment]
https://github.com/Zakhar-Khmurych

**Comment by ykhadnevich** [comment]
https://github.com/ykhadnevich

**Comment by omostovyijr** [comment]
https://github.com/omostovyijr

**Comment by ISukhoiarska** [comment]
https://github.com/ISukhoiarska

**Comment by okorshunovs** [comment]
https://github.com/okorshunovs/test2.git

**Comment by nastia4464** [comment]
https://github.com/nastia4464

**Comment by kmirik999** [comment]
https://github.com/kmirik999?tab=repositories

**Comment by complectzero** [comment]
https://github.com/complectzero

**Comment by bugarenko** [comment]
https://github.com/bugarenko/Bugarenko
